name: Flutter CI/CD
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter test
  build-android:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: |
          KEYSTORE_PATH=$RUNNER_TEMP/keystore.jks
          echo -n $KEYSTORE | base64 --decode > $KEYSTORE_PATH

          KEY_PROPERTIES_PATH=android/key.properties
          echo "storePassword=$STORE_PASSWORD" >> $KEY_PROPERTIES_PATH
          echo "keyPassword=$KEY_PASSWORD"     >> $KEY_PROPERTIES_PATH
          echo "keyAlias=alias"                >> $KEY_PROPERTIES_PATH
          echo "storeFile=$KEYSTORE_PATH"      >> $KEY_PROPERTIES_PATH
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
  deploy-android:
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: apk
      - run: curl -sL https://firebase.tools | bash
      - run: firebase appdistribution:distribute app-release.apk --app $APP_ID --groups $TESTER_GROUP
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          APP_ID: 1:xxxxxxxxxx:android:xxxxxxxxxx
          TESTER_GROUP: my-test-group
  build-ios:
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          KEYCHAIN_PASSWORD=$(node -p "Math.random().toString(36)")
          KEYCHAIN_PATH=$RUNNER_TEMP/build.keychain
          CERTIFICATE_PATH=$RUNNER_TEMP/build.p12

          # keychain作成
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # 証明書をkeychainにインポート
          echo -n "$CERTIFICATE_P12" | base64 --decode > $CERTIFICATE_PATH
          security import $CERTIFICATE_PATH -P "$CERTIFICATE_P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
        env:
          CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
          CERTIFICATE_P12_PASSWORD: ${{ secrets.CERTIFICATE_P12_PASSWORD }}
      - run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n "$PROVISION_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/build.mobileprovision
        env:
          PROVISION_PROFILE: ${{ secrets.PROVISION_PROFILE }}
      - run: flutter build ipa --export-options-plist=ios/ExportOptions.plist
      - uses: actions/upload-artifact@v2
        with:
          name: ipa
          path: build/ios/ipa/myfirstapp.ipa
  deploy-ios:
    needs: build-ios
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ipa
      - run: curl -sL https://firebase.tools | bash
      - run: firebase appdistribution:distribute myfirstapp.ipa --app $APP_ID --groups $TESTER_GROUP
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          APP_ID: 1:xxxxxxxxxx:ios:xxxxxxxxxx
          TESTER_GROUP: my-test-group
